# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example Asio application
#'
#' This function implements a very simple http client. It follows the \code{http_client.cpp}
#' example in the Asio documentation but has been adapted to be used as an example function
#' here.
#' @param host A character variable with an internet host name
#' @param path A character variable with an accessible path
#' @return Nothing is returned as the function is invoked for its a side-effect of display
#' what is retrieved.
#' @examples
#' \dontrun{
#' ## now commented-out / inactive as the redirect upsets R's own checking
#' httpClient("www.apache.org", "/robots.txt")
#' }
httpClient <- function(host, path) {
    invisible(.Call(`_RcppAsioExample_httpClient`, host, path))
}

